package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RestaurarPassword extends javax.swing.JFrame {

    String user = "", user_update = "";

    public RestaurarPassword() {
        initComponents();
        user = Login.user;
        user_update = GestionarUsuarios.user_update;

        setSize(360, 260);
        setResizable(false);
        setTitle("Cambio de Contraseña para " + user_update);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Contraseña = new javax.swing.JLabel();
        jLabel_Contraseña1 = new javax.swing.JLabel();
        txt_Contraseña = new javax.swing.JPasswordField();
        txt_ContraseñaConfirmacion = new javax.swing.JPasswordField();
        jButton_Restaurar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Cambio de contraseña");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel_Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Nueva Contraseña:");
        getContentPane().add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel_Contraseña1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña1.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel_Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_Contraseña.setBackground(new java.awt.Color(153, 153, 153));
        txt_Contraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_Contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_ContraseñaConfirmacion.setBackground(new java.awt.Color(153, 153, 153));
        txt_ContraseñaConfirmacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ContraseñaConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_ContraseñaConfirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ContraseñaConfirmacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_ContraseñaConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        jButton_Restaurar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_Restaurar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Restaurar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Restaurar.setText("Restaurar Contraseña");
        jButton_Restaurar.setBorder(null);
        jButton_Restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RestaurarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Restaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RestaurarActionPerformed

        String password, confirmacion_password;

        password = txt_Contraseña.getText().trim();
        confirmacion_password = txt_ContraseñaConfirmacion.getText().trim();

        if (!password.equals("") && !confirmacion_password.equals("")) {
            
            if (password.equals(confirmacion_password)) {

                try {
                    
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement("update usuarios set password=? where username = '" + user_update + "'");
                    
                    pst.setString(1, password);
                    
                    pst.executeUpdate();
                    cn.close();
                    
                    txt_Contraseña.setBackground(Color.GREEN);
                    txt_ContraseñaConfirmacion.setBackground(Color.GREEN);
                    
                    JOptionPane.showMessageDialog(null, "Restauracion exitosa.");
                    this.dispose();
                    
                } catch (SQLException e) {
                    System.out.println("Error en restaurar contraseña" + e);
                }
                
            } else {                
                txt_ContraseñaConfirmacion.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }

        } else {
            txt_Contraseña.setBackground(Color.red);
            txt_ContraseñaConfirmacion.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No se admiten contraseñas vacias");
        }

    }//GEN-LAST:event_jButton_RestaurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Restaurar;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_Contraseña1;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPasswordField txt_Contraseña;
    private javax.swing.JPasswordField txt_ContraseñaConfirmacion;
    // End of variables declaration//GEN-END:variables
}
